/* Generated by powerful Codeforces Tool
 * Author: W_X_Dai
 * Time: 2022-10-15 23:18:19
**/

#include <bits/stdc++.h>
#define int long long
#define eb emplace_back
#define pii pair<int,int>
#define ff first
#define ss second
#define m_p make_pair

using namespace std;

const int N=1e5+5;

int n,arr[N];

inline void init(){
	n=3;
	for(int i=0;i<n;++i)cin >>arr[i];
}

inline void sol(){
	sort(arr,arr+3);
    cout<<(arr[1]+arr[0]==arr[2] ? "YES" : "NO")<<'\n';
}

int32_t main() {
    ios::sync_with_stdio(0),cin.tie(0);
    int t;cin >>t;
    while(t--)init(),sol();
    return 0;
}
