/* Generated by powerful Codeforces Tool
 * Author: W_X_Dai
 * Time: 2022-08-30 23:20:44
**/

#include <bits/stdc++.h>
#define int long long
#define eb emplace_back
#define pii pair<int,int>
#define ff first
#define ss second
#define m_p make_pair

using namespace std;

const int N=1e5+5;

int n,ans;
string s;

inline void init(){
    ans=0;
    cin >>n>>s;
    for(int i=0;i<n;++i){
        if(s[i]=='L')ans+=i;
        if(s[i]=='R')ans+=n-1-i;
    }
    return;
}

inline int lc(int i){
    return i;
}

inline int rc(int i){
    return n-1-i;
}

inline void sol(){
    init();//cout<<ans<<'\n';
    vector<int> cnt;
    set<int> se;
    for(int i=0;i<(n>>1);++i){
        int l=i,r=n-1-i;
    //    cout<<l<<" "<<r<<'\n';
        if(s[l]=='L')ans+=max(0LL,rc(l)-lc(l));
        if(s[l]=='L')cnt.eb(ans);
    //    se.insert(ans);
        if(s[r]=='R')ans+=max(0LL,lc(r)-rc(r));
        if(s[r]=='R')cnt.eb(ans);
    //    se.insert(ans);
    }
    sort(cnt.begin(),cnt.end());
    for(int i:cnt)cout<<i<<" ";
    for(int i=cnt.size();i<n;++i)cout<<ans<<" ";



    // sort(cnt.begin(),cnt.end());
    // for(int i=cnt.size();i<n;++i)cnt.eb(ans);
    // for(int i:cnt)cout<<i<<" ";
    cout<<'\n';
    return;
}

int32_t main() {
    ios::sync_with_stdio(0),cin.tie(0);
    int t;cin >>t;
    while(t--)sol();
    return 0;
}
