/* Generated by powerful Codeforces Tool
 * Author: W_X_Dai
 * Time: 2022-10-22 22:27:11
**/

#include <bits/stdc++.h>
#define int long long
#define eb emplace_back
#define pii pair<int,int>
#define ff first
#define ss second
#define m_p make_pair

using namespace std;

const int N=2e5+5;

string s1,s2;
int a,b;

inline void init(){
	cin >>s1>>s2;
    if(s1[s1.size()-1]=='S')a=1;
    if(s2[s2.size()-1]=='S')b=1;


    if(s1[s1.size()-1]=='M')a=2;
    if(s2[s2.size()-1]=='M')b=2;

    if(s1[s1.size()-1]=='L')a=3;
    if(s2[s2.size()-1]=='L')b=3;
}

inline void sol(){
	int ans;//0:> 1:= 2:<

    if(s1==s2)ans=1;
    else if(a==b){
        ans=(s1.size()>s2.size() ? 0 : 2);
        if(a==1)ans=2-ans;
    }else if(a<b)ans=2;
    else if(a>b)ans=0;

    string s=">=<";
    cout<<s[ans]<<'\n';

}

int32_t main() {
    ios::sync_with_stdio(0),cin.tie(0);
    int t;cin >>t;
    while(t--)init(),sol();
    return 0;
}
