/* Generated by powerful Codeforces Tool
 * Author: W_X_Dai
 * Time: 2022-08-29 04:21:19
**/

#include <bits/stdc++.h>
#define int long long
#define eb emplace_back
#define pii pair<int,int>
#define ff first
#define ss second
#define m_p make_pair

using namespace std;

const int N=1e5+5;

int n,h,m;

inline void sol(){
        cin >> n >> h >> m;
        int time = 60 * h + m;
        int ans = 26 * 60;
        for (int i = 0; i < n; i++)
        {
            cin >> h >> m;
            int t = 60 * h + m - time;
            if (t < 0)
                t += 24 * 60;
            ans = min(ans, t);
        }
        cout << ans / 60 << " " << ans % 60 << '\n';
}

int32_t main() {
    ios::sync_with_stdio(0),cin.tie(0);
    int t;cin >>t;
    while(t--)sol();
    return 0;
}
