/* Generated by powerful Codeforces Tool
 * Author: W_X_Dai
 * Time: 2022-08-30 23:00:33
**/

#include <bits/stdc++.h>
#define int long long
#define eb emplace_back
#define pii pair<int,int>
#define ff first
#define ss second
#define m_p make_pair

using namespace std;

const int N=1e5+5;

inline void sol(){
    string s1,s2;
    int n,ok=1;

    cin >>n>>s1>>s2;
    for(int i=0;i<n;++i){
        if(s1[i]=='G')s1[i]='B';
        if(s2[i]=='G')s2[i]='B';
    }

    cout<<(s1==s2 ? "YES" : "NO")<<'\n';
    return;
}

int32_t main() {
    ios::sync_with_stdio(0),cin.tie(0);
    int t;cin >>t;
    while(t--)sol();
    return 0;
}
