/* Generated by powerful Codeforces Tool
 * Author: W_X_Dai
 * Time: 2022-10-16 22:35:02
**/

#include <bits/stdc++.h>
#define int long long
#define eb emplace_back
#define pii pair<int,int>
#define ff first
#define ss second
#define m_p make_pair

using namespace std;

const int N=1e3+5;

int n,arr[N];
char dict[N];
string s;

inline void init(){
	cin >>n;
	for(int i=0;i<n;++i)cin >>arr[i];
    for(int i=0;i<100;++i)dict[i]='0';
    cin >>s;
}

inline void sol(){
    for(int i=0;i<n;++i){
        int id=arr[i];
        if(dict[id]=='0'){
            dict[id]=s[i];
        }else{
            if(dict[id]!=s[i]){
                cout<<"NO\n";
                return;
            }
        }
    }
    cout<<"YES\n";
    return;
}

int32_t main() {
    ios::sync_with_stdio(0),cin.tie(0);
    int t;cin >>t;
    while(t--)init(),sol();
    return 0;
}
