/* Generated by powerful Codeforces Tool
 * Author: W_X_Dai
 * Time: 2022-08-31 00:03:59
**/

#include <bits/stdc++.h>
#define int long long
#define eb emplace_back
#define pii pair<int,int>
#define ff first
#define ss second
#define m_p make_pair

using namespace std;

const int N=1e5+5;

int n,m,mp[55][55];
char x;

inline void init(){
    memset(mp,0,sizeof(mp));
}

inline int res(int j,int i){

    int cnt=max({
        mp[i][j]+mp[i+1][j]+mp[i][j+1],
        mp[i][j]+mp[i+1][j]+mp[i+1][j+1],
        mp[i][j]+mp[i][j+1]+mp[i+1][j+1],
        mp[i][j]+mp[i][j+1]+mp[i-1][j+1]
    });
    cout<<cnt<<'\n';
    if(cnt!=3)return 0;

    if(mp[i][j]+mp[i+1][j]+mp[i][j+1]==3){
        int cnt=mp[i+2][j]+mp[i+2][j+1]+mp[i+1][j+1]+mp[i+1][j+2]+
                mp[i][j+2]+mp[i-1][j+1]+mp[i-1][j+2];
        if(cnt){cout<<1<<'\n';return 0;}
        else{
            mp[i][j]=mp[i+1][j]=mp[i][j+1]=0;
            return 1;
        }
    }
    if(mp[i][j]+mp[i+1][j]+mp[i+1][j+1]==3){
        int cnt=mp[i-1][j+1]+mp[i][j+1]+mp[i][j+2]+mp[i+1][j+2]+
                mp[i+2][j]+mp[i+2][j+1]+mp[i+2][j+2];
        if(cnt){cout<<2<<'\n';return 0;}
        else{
            mp[i][j]=mp[i+1][j]=mp[i+1][j+1]=0;
            return 1;
        }
    }
    if(mp[i][j]+mp[i][j+1]+mp[i+1][j+1]==3){
        int cnt=mp[i-1][j+1]+mp[i-1][j+2]+mp[i-1][j+3]+mp[i][j+2]+
                mp[i+1][j]+mp[i+1][j+2]+mp[i+2][j]+mp[i+2][j+1]+
                mp[i+2][j+2];
        if(cnt){cout<<3<<'\n';return 0;}
        else{
            mp[i][j]=mp[i][j+1]=mp[i+1][j+1]=0;
            return 1;
        }

    }
    if(mp[i][j]+mp[i][j+1]+mp[i-1][j+1]==3){
        int cnt=mp[i-2][j+1]+mp[i-2][j+2]+mp[i-1][j+2]+mp[i][j+2]+
                mp[i+1][j]+mp[i+1][j+1]+mp[i+1][j+2];
        if(cnt){cout<<4<<'\n';return 0;}
        else{
            mp[i][j]=mp[i][j+1]=mp[i-1][j+1]=0;
            return 1;
        }
    }
}

inline void sol(){
    init();
    cin >>n>>m;
    for(int i=1;i<=n;++i){
        for(int j=1;j<=m;++j){
            cin >>x;
            mp[i][j]=(x=='.' ? 0 : 1);
        }
    }

    if(n==1 || m==1){cout<<"NO";return;}

    for(int i=1;i<=n;++i){
        for(int j=1;j<=n;++j){
            if(mp[i][j]){
                if(!res(i,j)){
                    cout<<"NO\n";
                    return;
                }
            }
        }
    }
    cout<<"YES\n";
    return;
}

int32_t main() {
    ios::sync_with_stdio(0),cin.tie(0);
    int t;cin >>t;
    while(t--)sol();
    return 0;
}
