/* Generated by powerful Codeforces Tool
 * Author: W_X_Dai
 * Time: 2022-08-30 23:06:48
**/

#include <bits/stdc++.h>
#define int long long
#define eb emplace_back
#define pii pair<int,int>
#define ff first
#define ss second
#define m_p make_pair

using namespace std;

const int N=1e5+5;

inline void sol(){
    int ans[3]={0},n;
    map<string,int> mp;
    string s[3][1005];

    cin >>n;
    for(int i=0;i<3;++i){
        for(int j=0;j<n;++j){
            string tmp;cin >>tmp;
            s[i][j]=tmp;
            ++mp[tmp];
        }
    }

    for(int i=0;i<3;++i){
        for(int j=0;j<n;++j){
            string tmp=s[i][j];
            if(mp[tmp]==1)ans[i]+=3;
            if(mp[tmp]==2)ans[i]+=1;
        }
    }

    cout<<ans[0]<<" "<<ans[1]<<" "<<ans[2]<<'\n';
    return;
}   

int32_t main() {
    ios::sync_with_stdio(0),cin.tie(0);
    int t;cin >>t;
    while(t--)sol();
    return 0;
}
