/* Generated by powerful Codeforces Tool
 * Author: W_X_Dai
 * Time: 2022-08-29 04:29:23
**/

#include <bits/stdc++.h>
//#define int long long
#define eb emplace_back
#define pii pair<int,int>
#define ff first
#define ss second
#define m_p make_pair

using namespace std;

const int N=1e5+5;

int n;


inline void sol(){
    vector<int> v;
    cin >>n;
    
    for(int i=9;i>0;--i){
        if(n>i)v.eb(i),n-=i;
        else{v.eb(n);break;}
    }

    for(int i=v.size()-1;i>=0;--i)cout<<v[i];
    cout<<'\n';
}

int32_t main() {
    ios::sync_with_stdio(0),cin.tie(0);
    int t;cin >>t;
    while(t--)sol();
    return 0;
}
