/* Generated by powerful Codeforces Tool
 * Author: W_X_Dai
 * Time: 2022-10-16 22:35:02
**/

#include <bits/stdc++.h>
#define int long long
#define eb emplace_back
#define pii pair<int,int>
#define ff first
#define ss second
#define m_p make_pair

using namespace std;

const int N=1e5+5;

int n,q,m,x,arr[N];
int oddsum,oddn,evensum,evenn;

inline void init(){
	cin >>n>>q;
	for(int i=0;i<n;++i)cin >>arr[i];
    oddsum=0,oddn=0,evensum=0,evenn=0;
}

inline void sol(){
	for(int i=0;i<n;++i){
        if(arr[i] & 1)++oddn,oddsum+=arr[i];
        else ++evenn,evensum+=arr[i];
    }
    for(int i=0;i<q;++i){
        cin >>m>>x;
        if(m==0){
            if(x & 1){
                oddsum+=x*evenn+evensum;
                oddn=n,evenn=0,evensum=0;
            }else{
                evensum+=x*evenn;
            }
        }else{
            if(x & 1){
                evensum+=x*oddn+oddsum;
                evenn=n,oddn=0,oddsum=0;
            }else{
                oddsum+=x*oddn;
            }
        }
        cout<<oddsum+evensum<<'\n';
    }
    return;

}

int32_t main() {
    ios::sync_with_stdio(0),cin.tie(0);
    int t;cin >>t;
    while(t--)init(),sol();
    return 0;
}
