/* Generated by powerful Codeforces Tool
 * Author: W_X_Dai
 * Time: 2022-08-30 23:34:16
**/

#include <bits/stdc++.h>
#define int long long
#define eb emplace_back
#define pii pair<int,int>
#define ff first
#define ss second
#define m_p make_pair

using namespace std;

const int N=1e5+5;

int n,q,h1,h2,w1,w2;
int arr[N];
int mp[1005][1005];

inline void sol(){
    memset(mp,0,sizeof(mp));
    cin >>n>>q;
    vector<int> v[1005];
    for(int i=0;i<n;++i){
        int a,b;
        cin >>a>>b;
        v[a].eb(b);
    }

    for(int i=1;i<=1000;++i)sort(v[i].begin(),v[i].end());

    int ans=0;
    for(int i=0;i<q;++i){
        cin >>h1>>h2>>w1>>w2;
        for(int j=h1+1;j<h2;++j){
            if(v[j].empty())continue;
            int l=upper_bound(v[j].begin(),v[j].end(),w1)-v[j].begin();
            for(int k=l;v[j][k]<w2;++k)ans+=j*v[j][k];
        }
    }
    cout<<ans<<'\n';
    return;
}

int32_t main() {
    ios::sync_with_stdio(0),cin.tie(0);
    int t;cin >>t;
    while(t--)sol();
    return 0;
}
