/* Generated by powerful Codeforces Tool
 * Author: W_X_Dai
 * Time: 2022-10-16 22:35:02
**/

#include <bits/stdc++.h>
#define int long long
#define eb emplace_back
#define pii pair<int,int>
#define ff first
#define ss second
#define m_p make_pair

using namespace std;

const int N=1e5+1;

int a,b,c,d;
int pri[N];

inline void init(){
	cin >>a>>b>>c>>d;
}

inline void sol(){
    int x=a+1,z=a*b;
    for(x=a+1;x<=c;++x){
        int t=z/__gcd(z,x);
        int rest=b-b%t+t;
        if(rest<=d ){
            cout<<x<<" "<<rest<<'\n';
            return;
        }
    }
    cout<<"-1 -1\n";
    return;
}

int32_t main() {
    ios::sync_with_stdio(0),cin.tie(0);
    int t;cin >>t;
    while(t--)init(),sol();
    return 0;
}
