/* Generated by powerful Codeforces Tool
 * Author: W_X_Dai
 * Time: 2022-08-29 04:23:51
**/

#include <bits/stdc++.h>
#define int long long
#define eb emplace_back
#define pii pair<int,int>
#define ff first
#define ss second
#define m_p make_pair

using namespace std;

const int N=2e5+5;

inline void sol(){
    int n,arr[N],vis[N]={0};

    cin >>n;
    for(int i=1;i<=n;++i)cin >>arr[i];
    for(int i=n;i>0;--i){
        if(vis[arr[i]]){cout<<i<<'\n';return;}
        vis[arr[i]]=1;
    }
    cout<<"0\n";
    return;
}

int32_t main() {
    ios::sync_with_stdio(0),cin.tie(0);
    int t;cin >>t;
    while(t--)sol();
    return 0;
}
