/* Generated by powerful Codeforces Tool
 * Author: W_X_Dai
 * Time: 2022-10-16 22:35:02
**/

#include <bits/stdc++.h>
#define int long long
#define eb emplace_back
#define pii pair<int,int>
#define ff first
#define ss second
#define m_p make_pair

using namespace std;

const int N=2e5+5;

int n,m,arr[N],pre[N];
vector<int> v;

inline void init(){
	cin >>n;m=0;v.clear();
	for(int i=1;i<=n;++i)cin >>arr[i],pre[i]=0;
}

inline void divi(int x){
    while(!(x & 1)){
        ++m;x>>=1;
    }
}

inline void diviid(int x){
    int cnt=0;
    while(!(x & 1)){
        ++cnt;x>>=1;
    }
    v.eb(cnt);
}

inline void sol(){
	for(int i=1;i<=n;++i){
        diviid(i),divi(arr[i]);
    }
//   cout<<m<<" "<<n<<'\n';
    if(m>=n){
        cout<<0<<'\n';
        return;
    }

    sort(v.begin(),v.end(),greater<int>());
    for(int i=1;i<=n;++i){
        pre[i]=v[i-1];
    }

    for(int i=1;i<=n;++i){
        pre[i]+=pre[i-1];//cout<<v[i]<<'\n';
        if(pre[i]+m>=n){
            cout<<i<<'\n';
            return;
        }
    }
    cout<<"-1\n";
    return;
}

int32_t main() {
    ios::sync_with_stdio(0),cin.tie(0);
    int t;cin >>t;
    while(t--)init(),sol();
    return 0;
}
